name: planet
channels:
  - defaults
dependencies:
  - setuptools
  - numpy>=1.15.4
  - scipy>=1.1.0
  - click>=7.0
  - rasterio>=1.0.21
  - py-xgboost>=0.80
#   - py-xgboost-gpu # [not win]
  - tqdm>=4.28.1
  - numba>=0.42.0
  - scikit-learn>=0.20.2
  - pip:
    - planet>=1.2.2
    - sphinx-click>=2.0.2.dev1
